# Generated by Django 3.0.6 on 2020-06-27 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgdespacho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('monto', models.IntegerField()),
                ('idpaquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgdespacho.Paquete')),
            ],
        ),
    ]
